apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "default-backend.fullname" . }}-pages
  labels:
    {{- include "default-backend.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.pages | nindent 2 }}
